// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCCbFJhFcus6fi8dJ2SzUM3485dJC5W0',
    appId: '1:807366994297:web:37e30dfadbf233576527a8',
    messagingSenderId: '807366994297',
    projectId: 'worktime-97bc8',
    authDomain: 'worktime-97bc8.firebaseapp.com',
    storageBucket: 'worktime-97bc8.appspot.com',
    measurementId: 'G-9EEQYDLXVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVe2mfuIpegP44fQWfbi-SJgZASktEQU',
    appId: '1:807366994297:android:5c816cdbf2e4386f6527a8',
    messagingSenderId: '807366994297',
    projectId: 'worktime-97bc8',
    storageBucket: 'worktime-97bc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyU1TLtKGw5W6ofkRwyVWI5d22Kh-13c',
    appId: '1:807366994297:ios:d0b5ecfde7d5560f6527a8',
    messagingSenderId: '807366994297',
    projectId: 'worktime-97bc8',
    storageBucket: 'worktime-97bc8.appspot.com',
    iosBundleId: 'com.example.worktime',
  );
}
